default_install_hook_types: [pre-commit, pre-push]
fail_fast: false

repos:
  - repo: local
    hooks:
      - id: check
        name: check frontend and backend formatting, lint, and types
        entry: make check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: test
        name: test frontend and backend
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
