# Generated by Django 6.1 on 2026-08-28 03:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('project-manager', 'Pm'), ('contributor', 'Contributor')], default='contributor', max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('time_zone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('space_code', models.CharField(max_length=5, unique=True)),
                ('description', models.TextField(default='', max_length=500, null=True)),
                ('icon_url', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
