# Generated by Django 6.1 on 2026-09-15 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_orginvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0a45f-4f48-768a-93e8-5780f8e5a5a7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
