# Generated by Django 6.1 on 2026-09-15 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_orginvitation_email_alter_orginvitation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orginvitation',
            name='recipient',
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='org_invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0a468-2ae2-7613-b03c-94344e1e2aee'), editable=False, primary_key=True, serialize=False),
        ),
    ]
