# Generated by Django 6.1 on 2026-09-15 09:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_orginvitation_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0a46f-f6d0-76a7-a26c-d52a5b3963dd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
