# Generated by Django 6.1 on 2026-09-15 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_orginvitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0a479-f023-7437-852c-a22ca8221d83'), editable=False, primary_key=True, serialize=False),
        ),
    ]
