# Generated by Django 6.1 on 2026-09-15 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_orginvitation_accepted_alter_orginvitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0a47b-04df-7211-b12a-99c302d537f2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
