# Generated by Django 6.1 on 2026-09-15 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_orginvitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0a47c-3385-7766-9c4d-80d3b3901858'), editable=False, primary_key=True, serialize=False),
        ),
    ]
