# Generated by Django 6.1 on 2026-09-15 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_orginvitation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvitation',
            name='text_message',
            field=models.TextField(default='Invitation :)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0a5a1-781d-7218-a7ac-846c69e812e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
