# Generated by Django 6.1 on 2026-10-01 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_orginvitation_text_message_alter_orginvitation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0f91c-e250-7537-90a5-47c04e8ac7f3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='text_message',
            field=models.TextField(default='Invitation :)', max_length=500),
        ),
    ]
