# Generated by Django 6.1 on 2026-10-01 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_orginvitation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01a0f91d-62ea-7185-bf1f-bd7a5b411f38'), editable=False, primary_key=True, serialize=False),
        ),
    ]
