# Generated by Django 6.1 on 2026-10-07 09:52

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_alter_orginvitation_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='expired_at',
            field=models.DateTimeField(default=organizations.models.expired_date_at),
        ),
    ]
