# Generated by Django 6.1 on 2026-10-07 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_alter_orginvitation_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 7, 21, 12, 3, 31500, tzinfo=datetime.timezone.utc)),
        ),
    ]
