# Generated by Django 6.0.8 on 2026-08-12 13:04

import pulse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workitem',
            name='workitem_due_date_not_in_past',
        ),
        migrations.AlterField(
            model_name='workitem',
            name='due_date',
            field=models.DateTimeField(validators=[pulse.models.validate_not_past]),
        ),
    ]
