# Generated by Django 6.0.8 on 2026-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_remove_workitem_workitem_due_date_not_in_past_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='icon_url',
            field=models.CharField(max_length=500),
        ),
    ]
