# Generated by Django 6.0.8 on 2026-08-12 14:47

import django.core.validators
import django.db.models.deletion
import pulse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_alter_member_avatar_url_alter_workspace_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar_url',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='time_zone',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='due_date',
            field=models.DateTimeField(null=True, validators=[pulse.models.validate_not_past]),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='estimated_time',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='time_spent',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
