# Generated by Django 6.1 on 2026-08-28 03:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import workitems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='', null=True)),
                ('status', models.CharField(choices=[('to do', 'Todo'), ('in progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('test', 'Test'), ('test done', 'Test Pass')], default='to do', max_length=11)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('major', 'Major')], default='high', max_length=11)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(validators=[workitems.models.validate_not_past])),
                ('estimated_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('time_spent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_to', to='organizations.member')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_by', to='organizations.member')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
            ],
        ),
    ]
