# Generated by Django 6.0.8 on 2026-08-12 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0004_alter_member_avatar_url_alter_member_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
