# Generated by Django 6.0.8 on 2026-08-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0005_organization_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='description',
            field=models.TextField(default='', max_length=500, null=True),
        ),
    ]
