# Generated by Django 6.1 on 2026-08-21 20:41

import datetime
import django.core.validators
import django.db.models.deletion
import pulse.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0006_alter_organization_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.date(2026, 8, 21), validators=[pulse.models.validate_not_past]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workitem',
            name='estimated_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='time_spent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
