# Generated by Django 6.0.8 on 2026-08-23 14:41

import pulse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0008_alter_member_user_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='time_zone',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='due_date',
            field=models.DateField(validators=[pulse.models.validate_not_past]),
        ),
    ]
