name: Lint and test

on:
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: backend/uv.lock

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install backend dependencies
        run: uv sync --all-groups --frozen
        working-directory: backend

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile
        working-directory: frontend

      - name: Run pre-commit checks
        run: uv run --directory backend pre-commit run --all-files

  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: backend/uv.lock

      - name: Install backend dependencies
        run: uv sync --all-groups --frozen
        working-directory: backend

      - name: Run backend tests
        run: uv run pytest
        working-directory: backend

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: bun install --frozen-lockfile
        working-directory: frontend

      - name: Run frontend tests
        run: bun test
        working-directory: frontend
